import { z } from "zod"

export const jobPostingSchema = z.object({
  externalReference: z.string().optional(),
  source: z.string().optional(),
  sourceUrl: z.string().url().optional().or(z.literal("")),
  jobTitle: z.string().min(1, "Job title is required"),
  companyName: z.string().min(1, "Company name is required"),
  companyDivision: z.string().optional(),
  organizationalUnit: z.string().optional(),
  roleCategory: z.string().optional(),
  roleProfile: z.string().optional(),
  seniorityLevel: z.string().min(1, "Seniority level is required"),
  workLocation: z.union([z.string(), z.array(z.string())]), // Handle string or JSON array
  employmentType: z.string().min(1, "Employment type is required"),
  contractDuration: z.string().optional(),
  startDate: z.string().optional().nullable().transform(val => val ? new Date(val) : null),
  endDate: z.string().optional().nullable().transform(val => val ? new Date(val) : null),
  extensionPossible: z.boolean().optional(),
  description: z.string().min(1, "Description is required"),
  missionContext: z.string().optional(),
  responsibilities: z.union([z.string(), z.array(z.string())]),
  objectives: z.union([z.string(), z.array(z.string())]),
  education: z.union([z.string(), z.array(z.string())]).optional().nullable(),
  experience: z.union([z.string(), z.array(z.string())]).optional().nullable(),
  skills: z.union([z.string(), z.array(z.string())]).optional().nullable(),
  languages: z.union([z.string(), z.array(z.string())]),
  industry: z.string().optional(),
  domain: z.string().optional(),
  travelRequired: z.string().optional(),
  salaryRange: z.union([z.string(), z.object({ min: z.number(), max: z.number(), currency: z.string() })]).optional().nullable(),
  applicationMethod: z.string().optional(),
  contactPerson: z.union([z.string(), z.object({ name: z.string(), email: z.string().email() })]).optional().nullable(),
  applicationDeadline: z.string().optional().nullable().transform(val => val ? new Date(val) : null),
  status: z.enum(["ACTIVE", "DRAFT", "ARCHIVED", "FILLED"]).default("ACTIVE"),
})

export const candidateSchema = z.object({
  firstName: z.string().min(1, "First name is required"),
  lastName: z.string().min(1, "Last name is required"),
  email: z.string().email("Invalid email address"),
  phoneNumber: z.string().optional(),
  desiredRoles: z.union([z.string(), z.array(z.string())]),
  skills: z.union([z.string(), z.array(z.string())]),
  industries: z.union([z.string(), z.array(z.string())]),
  seniorityLevel: z.string().optional(),
  certifications: z.union([z.string(), z.array(z.string())]),
  location: z.string().optional(),
  profileDataJson: z.any().optional(),
})
